### ISSUE TITLE
Mau nanya

### ISSUE THREAD

**Issue by wandesay75** [raihanprojecthub/travelaku-tailwind-css#1]
bang ini web hostingan mu kemana bang?? kok 404 not found

**Comment by raihanprojecthub** [comment]
Oke Terima Kasih atas ulasannya nanti saya coba perbaiki.

**Comment by raihanprojecthub** [comment]
> bang ini web hostingan mu kemana bang?? kok 404 not found

Oke Terima Kasih atas ulasannya nanti saya akan coba perbaiki.
